name: hello-world
on: push
jobs: 
    build: 
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - run: echo "$(cat hello_world.txt)"
        - name: Use node Js
          uses: actions/checkout/@v3
          with: 
            node-version: '20'
        - run: npm install
        - run :  npm run build
    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Check  code
          uses: actions/checkout@v3
        - run: echo "$(cat hello_world.txt)"
        - name: Use node Js
          uses: actions/checkout/@v3
          with: 
            node-version: '20'
        - run: npm install
        - run : npm run test
      
        
