name: hello-world-workflow
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout/@v3
      - run: echo "$(cat hello_world.txt)"
      
